### PR TITLE
Fix a crash in the SearchActivity and improve its state management

### LINKED ISSUE #531: Search crashes when typing too fast
The app crashes on my phone when typing too fast in the search bar (Pixel XL, Android 8.1)

Repro:

1. Build from `develop`
2. Open search
3. Start typing very fast (I repro'd typing `daniele` but I don't think it matters) 
4. Observe the app crashing:

```
java.lang.IndexOutOfBoundsException: Index: 52, Size: 11
    at java.util.ArrayList.get(ArrayList.java:437)
    at net.squanchy.search.view.GridSpanSizeLookup.getSpanSize(GridSpanSizeLookup.kt:13)
    at android.support.v7.widget.GridLayoutManager$SpanSizeLookup.getSpanGroupIndex(GridLayoutManager.java:971)
    at android.support.v7.widget.GridLayoutManager.getSpanGroupIndex(GridLayoutManager.java:451)
    at android.support.v7.widget.GridLayoutManager.getRowCountForAccessibility(GridLayoutManager.java:125)
    at android.support.v7.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:9991)
    at android.support.v7.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:9951)
    at android.support.v7.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:61)
    at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateApi16Impl$1.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:126)
    at android.view.View.onInitializeAccessibilityNodeInfo(View.java:7343)
    at android.view.View.createAccessibilityNodeInfoInternal(View.java:7304)
    at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:26062)
    at android.view.View.createAccessibilityNodeInfo(View.java:7287)
    at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1147)
    at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:972)
    at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:336)
    at android.view.AccessibilityInteractionController.-wrap1(Unknown Source:0)
    at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1324)
    …
```

### PR DESCRIPTION
**Pull request by quiro91**
## Problem

A bug in the `GridSpanLookup` after the migration to `ListAdapter` caused a crash in the `SearchActivity`

## Solution

Use `ListAdapter.getItem` as only source of truth for retrieving an item from the adapter, plus some few more improvements pointed out in the code.

This closes #531

### Test(s) added

Unfortunately too Android to test

### Paired with

Nobody

### CODE REVIEW

File: app/src/main/java/net/squanchy/search/SearchActivity.kt [hunk 1]
```diff
@@ -123,9 +120,8 @@ class SearchActivity : AppCompatActivity(), SearchRecyclerView.OnSearchResultCli
         } else {
             emptyView.isInvisible = true
             searchRecyclerView.isVisible = true
-
-            searchRecyclerView.updateWith(searchResult, this)
         }
+        searchRecyclerView.updateWith(searchResult, this)
```
Comment (quiro91) [inline app/src/main/java/net/squanchy/search/SearchActivity.kt:124]: we now update the recyclerview even when there are no search result. This is done for consistency, since we now have animations for adapter changes. Otherwise the next search result would animate from the state x to the state x + 2, skipping x + 1 (empty adapter)

File: app/src/main/java/net/squanchy/search/SearchActivity.kt [hunk 2]
```diff
@@ -46,13 +46,16 @@ class SearchActivity : AppCompatActivity(), SearchRecyclerView.OnSearchResultCli
     private lateinit var searchTextWatcher: SearchTextWatcher
 
     private var hasQuery: Boolean = false
+    private lateinit var query: String
```
Comment (rock3r) [inline app/src/main/java/net/squanchy/search/SearchActivity.kt]: Maybe `pendingQuery`? Or `initialQuery`?

File: app/src/main/java/net/squanchy/search/SearchActivity.kt [hunk 3]
```diff
@@ -193,6 +189,11 @@ class SearchActivity : AppCompatActivity(), SearchRecyclerView.OnSearchResultCli
         }
     }
 
+    override fun onSaveInstanceState(outState: Bundle?) {
+        outState?.putString(QUERY_KEY, searchField.text?.toString())
```
Comment (rock3r) [inline app/src/main/java/net/squanchy/search/SearchActivity.kt:193]: ⚠️  Note that if the `outState` is null it's your responsibility to create it here and pass it down!

**Review by rock3r — CHANGES_REQUESTED** [review]

File: app/src/main/java/net/squanchy/search/SearchActivity.kt (hunk 3 above)
Comment (quiro91) [reply app/src/main/java/net/squanchy/search/SearchActivity.kt:193]: Are you sure about this? I think it's actually not null, it's just lacking the annotation as some other support library code. We use it also in the `HomeActivity` where we consider the `Bundle` not null

File: app/src/main/java/net/squanchy/search/SearchActivity.kt (hunk 2 above)
Comment (quiro91) [reply app/src/main/java/net/squanchy/search/SearchActivity.kt]: ac9e687

File: app/src/main/java/net/squanchy/search/SearchActivity.kt [hunk 4]
```diff
@@ -189,8 +189,8 @@ class SearchActivity : AppCompatActivity(), SearchRecyclerView.OnSearchResultCli
         }
     }
 
-    override fun onSaveInstanceState(outState: Bundle?) {
-        outState?.putString(QUERY_KEY, searchField.text?.toString())
+    override fun onSaveInstanceState(outState: Bundle) {
```
Comment (rock3r) [inline app/src/main/java/net/squanchy/search/SearchActivity.kt]: ❌ no, this **is** nullable. You need to _create_ it yourself if you get passed down null!

This will crash.

**Review by rock3r — CHANGES_REQUESTED** [review]

File: app/src/main/java/net/squanchy/search/SearchActivity.kt (hunk 4 above)
Comment (quiro91) [reply app/src/main/java/net/squanchy/search/SearchActivity.kt]: uhm ok, should I also change 
https://github.com/squanchy-dev/squanchy-android/blob/develop/app/src/main/java/net/squanchy/home/HomeActivity.kt#L193
and
https://github.com/squanchy-dev/squanchy-android/blob/develop/app/src/main/java/net/squanchy/schedule/tracksfilter/ScheduleTracksFilter.kt#L178
?

Comment (rock3r) [reply app/src/main/java/net/squanchy/search/SearchActivity.kt]: We should at the very least make sure we don't assume it's non-null

File: app/src/main/java/net/squanchy/search/SearchActivity.kt (hunk 3 above)
Comment (rock3r) [reply app/src/main/java/net/squanchy/search/SearchActivity.kt:193]: Google Kotlin samples leave it as nullable... but yeah they should really have annotations

**Review by rock3r — APPROVED** [review]
