### PR TITLE
SQ-390/Fix missing reveal on bottom nav

### LINKED ISSUE #390: BottomNavigationBar circular reveals don't work on Android 8.1+
As per title, the hacks we have in place to animate the colour reveals in the bottom nav bar stopped working as of Android 8.1.

### PR DESCRIPTION
**Pull request by rock3r**
After #312 actually broke the circular reveals even more than they were already, I finally had the time to check whether we could make them work on API 26-27.

Closes #390 

les-circles

### CODE REVIEW

File: app/src/main/java/net/squanchy/support/graphics/CircularRevealDrawable.java [hunk 1]
```diff
@@ -52,7 +52,7 @@ public void animateToColor(@ColorInt int newColor, @IntRange(from = 0) int durat
         revealDuration = durationMillis;
         pendingTargetColor = newColor;
         startAnimationOnNextDraw = true;
-        setColor(pendingTargetColor);
```
Comment (rock3r) [inline app/src/main/java/net/squanchy/support/graphics/CircularRevealDrawable.java:55]: This reverts 41babe629df2ab5ed8d42443ecdfa272703056b8

File: app/src/main/java/me/eugeniomarletti/renderthread/RenderThreadMethods.java [hunk 2]
```diff
@@ -22,7 +22,7 @@
 @SuppressLint("PrivateApi")     // This class wraps the private APIs we rely on
 final class RenderThreadMethods {
 
-    private static final int MAX_SUPPORTED_ANDROID_VERSION = 25;
```
Comment (rock3r) [inline app/src/main/java/me/eugeniomarletti/renderthread/RenderThreadMethods.java:25]: Tested on 8.1 preview 1 on Pixel XL. Works just fine!

**Review by danybony — APPROVED** [review]
LGTM

**Review by Takhion — APPROVED** [review]
👍
