### PR TITLE
SQ-219/Fix Twitter parsing

### LINKED ISSUE #219: Tweet parsing is failing
When Twitter sends us Tweets, we often get the URLs or hashtag indexes off by one.

Additionally, only the first URL of the Tweet is found, forgetting the others.

### PR DESCRIPTION
**Pull request by quiro91**
This PR fixes the parsing of tweets and shows photos on tweets (if any, just the first one tho).

This fixes #219.

 Before | After
 --- | ---
 tweets-before | tweets-after

### CODE REVIEW

**Review by rock3r — CHANGES_REQUESTED** [review]
Imma fix a few things given I'm alone here today

**Review by rock3r — APPROVED** [review]

File: app/src/main/java/net/squanchy/tweets/model/ParsedTweet.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
+package net.squanchy.tweets.model;
+
+import com.google.auto.value.AutoValue;
+
+import java.util.List;
+
+import net.squanchy.tweets.domain.view.HashtagEntity;
+import net.squanchy.tweets.domain.view.MentionEntity;
+import net.squanchy.tweets.domain.view.UrlEntity;
```
Comment (fourlastor) [inline app/src/main/java/net/squanchy/tweets/model/ParsedTweet.java]: do we really need to append `Entity`?

File: app/src/main/java/net/squanchy/tweets/parsing/Regex.java [hunk 2]
```diff
@@ -0,0 +1,18 @@
+package net.squanchy.tweets.parsing;
+
+import java.util.regex.Pattern;
+
+enum Regex {
+    MENTION(Pattern.compile("@\\w+")),
```
Comment (fourlastor) [inline app/src/main/java/net/squanchy/tweets/parsing/Regex.java]: what if  an hashtag/mention has non alphanumeric chars?

**Review by rock3r — CHANGES_REQUESTED** [review]
Actually, just not ready yet

File: app/src/main/java/net/squanchy/tweets/model/TweetSpannableText.java [hunk 3]
```diff
@@ -0,0 +1,17 @@
+package net.squanchy.tweets.model;
+
+import com.google.auto.value.AutoValue;
+
+@AutoValue
+public abstract class TweetSpannableText {
```
Comment (fourlastor) [inline app/src/main/java/net/squanchy/tweets/model/TweetSpannableText.java]: Hm I see this is used _for_ the spannables creation but it isn't a spannable itself, maybe it's worth renaming it

File: app/src/main/java/net/squanchy/tweets/util/TweetTextFormatter.java [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+    public TweetTextFormatter(TweetTextParser tweetTextParser) {
+        this.tweetTextParser = tweetTextParser;
+    }
+
+    public Spannable format(Tweet tweet) {
+        Spannable spannable = new SpannableString(tweet.text());
+
+        ParsedTweet parsedTweet = tweetTextParser.parse(tweet.text());
+
+        addUrlSpans(spannable, parsedTweet.urls());
```
Comment (fourlastor) [inline app/src/main/java/net/squanchy/tweets/util/TweetTextFormatter.java]: Why do we use 3 different classes (mention, hashtag and url) if then we leak the info (the template for the url) here? :tongue:

**Review by fourlastor — CHANGES_REQUESTED** [review]
I think this needs a bit more work before it's good to go.

As a side note, the parsing of stuff it's kind of complicated (and very much error prone) and maybe it's worth understanding what is causing the offset (e.g. asking in ASG) instead of rolling our own parsing.

**Review by rock3r — APPROVED** [review]

**Comment by rock3r** [comment]
Ok done the rework/refactor. @fourlastor on you :)

File: app/src/main/java/net/squanchy/tweets/service/TweetModelConverter.java [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+
+    private Optional<String> photoUrlMaybeFrom(List<String> urls) {
+        if (urls.isEmpty()) {
+            return Optional.absent();
+        }
+        return Optional.of(urls.get(0));
+    }
+
+    @AutoValue
+    abstract static class Range {
```
Comment (fourlastor) [inline app/src/main/java/net/squanchy/tweets/service/TweetModelConverter.java:74]: not a blocker but if that's used only internally I wouldn't bother with autovalue

File: app/src/main/java/net/squanchy/tweets/view/TweetItemView.java [hunk 6]
```diff
@@ -1,41 +1,71 @@
...
-import net.squanchy.tweets.util.TweetFormatter;
+import net.squanchy.tweets.domain.view.TweetViewModel;
 import net.squanchy.tweets.util.TwitterFooterFormatter;
 
 public class TweetItemView extends CardLayout {
 
-    private TextView tweetText;
-    private TweetFooterView tweetFooter;
+    @Nullable
+    private ImageLoader imageLoader;
```
Comment (fourlastor) [inline app/src/main/java/net/squanchy/tweets/view/TweetItemView.java:23]: not for this PR but I just thought about this: what if instead of making it nullable, we have somewhere a no-op implementation constant that we use in edit mode? I would really like to get rid of the extra logic because the image loader is `null`

It would become something like:

```java
if (isInEditMode()) {
  imageLoader = EditModeImageLoader.INSTANCE;
} else {
  imageLoader = blablaInstantiateImageLoader;
}
```

File: app/src/main/java/net/squanchy/tweets/view/TweetsAdapter.java [hunk 7]
```diff
@@ -30,23 +30,23 @@ public TweetViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
...
+        return tweets.isEmpty();
     }
 
-    public void updateWith(List<Tweet> tweets) {
-        tweetList.clear();
-        ArrayList<Tweet> receivedItems = new ArrayList<>(tweets);
-        receivedItems.addAll(tweetList);
-        tweetList = receivedItems;
+    public void updateWith(List<TweetViewModel> tweet) {
+        this.tweets.clear();
```
Comment (fourlastor) [inline app/src/main/java/net/squanchy/tweets/view/TweetsAdapter.java:46]: can we swap the dataset instead of doing this?

**Review by fourlastor — CHANGES_REQUESTED** [review]
Only one actual comment, the others aren't blockers for this PR

File: app/src/main/java/net/squanchy/tweets/service/TweetModelConverter.java (hunk 5 above)
Comment (rock3r) [reply app/src/main/java/net/squanchy/tweets/service/TweetModelConverter.java:74]: ...too late? XD

Comment (fourlastor) [reply app/src/main/java/net/squanchy/tweets/service/TweetModelConverter.java:74]: I said not a blocker indeed :P

File: app/src/main/java/net/squanchy/tweets/view/TweetItemView.java (hunk 6 above)
Comment (rock3r) [reply app/src/main/java/net/squanchy/tweets/view/TweetItemView.java:23]: What about in edit mode we have it injected directly (so doing it at the Dagger level if at all possible)?

File: app/src/main/java/net/squanchy/tweets/view/TweetsAdapter.java (hunk 7 above)
Comment (rock3r) [reply app/src/main/java/net/squanchy/tweets/view/TweetsAdapter.java:46]: Next PR 👍

**Review by fourlastor — APPROVED** [review]

File: app/src/main/java/net/squanchy/tweets/view/TweetItemView.java (hunk 6 above)
Comment (fourlastor) [reply app/src/main/java/net/squanchy/tweets/view/TweetItemView.java:23]: Hm I thought about that but I don't know if we can do it with sourcesets instead of doing it passing booleans around. If it's the latter I'd rather have it inside the view
